#version 460
layout(local_size_x=1) in;
layout(set=0,binding=0) uniform UniformData { uint value; } ub;
layout(set=1,binding=0) buffer StorageData { uint value; uint observed; uint challenge; uint magic; } sb;
layout(push_constant) uniform Constants { layout(offset=240) uint challenge; uint side; uint magic; uint reserved; } pc;
void main() { sb.observed=ub.value; sb.challenge=pc.challenge; sb.magic=pc.magic; }
