#version 460
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
layout(local_size_x = 64) in;
layout(constant_id = 0) const uint VARIANT = 1;
layout(buffer_reference, std430) buffer Words { uint w[]; };
layout(push_constant) uniform PC { Words dst; uint v; } pc;
void main()
{
   pc.dst.w[gl_LocalInvocationIndex] = pc.v * VARIANT + gl_LocalInvocationIndex;
}
